version: 0.2

phases:
  post_build:
    commands:
      - npm i -g serverless
      - cd ./server
      - npm i
      - sls deploy -s prod_in -v
      - cd ..
      - cd ./client
      - npm i
      - sls deploy -s prod_in -v


